/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BacktestBasicInfo: typeof import('./src/components/Backtest/BacktestBasicInfo.vue')['default']
    BacktestMetrics: typeof import('./src/components/Backtest/BacktestMetrics.vue')['default']
    BacktestTradesList: typeof import('./src/components/Backtest/BacktestTradesList.vue')['default']
    BacktestTradingStats: typeof import('./src/components/Backtest/BacktestTradingStats.vue')['default']
    CodeEditor: typeof import('./src/components/Common/CodeEditor.vue')['default']
    ConditionGroupHelp: typeof import('./src/components/Common/ConditionGroupHelp.vue')['default']
    ConditionLogicVisualizer: typeof import('./src/components/Common/ConditionLogicVisualizer.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./src/components/Common/EmptyState.vue')['default']
    IndicatorCalculation: typeof import('./src/components/Indicator/IndicatorCalculation.vue')['default']
    IndicatorDetailInfo: typeof import('./src/components/Indicator/IndicatorDetailInfo.vue')['default']
    IndicatorParameters: typeof import('./src/components/Indicator/IndicatorParameters.vue')['default']
    IndicatorResults: typeof import('./src/components/Indicator/IndicatorResults.vue')['default']
    LoadingSpinner: typeof import('./src/components/Common/LoadingSpinner.vue')['default']
    MainLayout: typeof import('./src/components/Layout/MainLayout.vue')['default']
    ProfitChart: typeof import('./src/components/Common/ProfitChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrategyBasicInfo: typeof import('./src/components/Strategy/StrategyBasicInfo.vue')['default']
    StrategyConditions: typeof import('./src/components/Strategy/StrategyConditions.vue')['default']
    StrategyDetailConditions: typeof import('./src/components/Strategy/StrategyDetailConditions.vue')['default']
    StrategyDetailIndicators: typeof import('./src/components/Strategy/StrategyDetailIndicators.vue')['default']
    StrategyDetailInfo: typeof import('./src/components/Strategy/StrategyDetailInfo.vue')['default']
    StrategyDetailRisk: typeof import('./src/components/Strategy/StrategyDetailRisk.vue')['default']
    StrategyIndicators: typeof import('./src/components/Strategy/StrategyIndicators.vue')['default']
    StrategyManager: typeof import('./src/components/Common/StrategyManager.vue')['default']
    StrategyRiskManagement: typeof import('./src/components/Strategy/StrategyRiskManagement.vue')['default']
    ThemeExample: typeof import('./src/components/Common/ThemeExample.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
